name: Test code

on:
  push:

jobs:
  build:
    name: Test application 🐍
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v5
        with:
          enable-cache: true
          cache-dependency-glob: "uv.lock"
          pyproject-file: "pyproject.toml"

      - name: Install the project
        run: uv sync --all-extras --dev

      - name: Create junit results directory
        run: mkdir -p junit

      - name: Install action
        run: uv pip install pytest-github-actions-annotate-failures

      - name: Build coverage file
        run: |
          uv run pytest --junitxml=pytest.xml --cov-report=term-missing:skip-covered --cov=src tests/ | tee pytest-coverage.txt

      - name: Upload coverage report
        uses: actions/upload-artifact@v4
        with:
          name: coverage-report
          path: ./pytest-coverage.txt
