name: Test and static analyze

on: [push]

jobs:
  build:
    name: Test application 🐍
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v5
        with:
          enable-cache: true
          cache-dependency-glob: "uv.lock"
          pyproject-file: "pyproject.toml"

      - name: Install the project
        run: uv sync --all-extras --dev

      - name: Create junit results directory
        run: mkdir -p junit

      - name: Test with pytest
        run: pytest tests.py --doctest-modules --junitxml=junit/test-results.xml --cov=com --cov-report=xml --cov-report=html

      - name: Install the code linting and formatting tool Ruff
        run: uv pip install ruff

      - name: Lint code with Ruff
        run: uv run ruff check --output-format=github --target-version=py311

      - name: Check code formatting with Ruff
        run: uv run ruff format --diff --target-version=py311
        continue-on-error: true
